=== S41d/xmlproject/Projet.dtd
<?xml encoding="UTF-8"?>
    <!ELEMENT boutique (rayon)+>
    <!ATTLIST boutique>

    <!ELEMENT rayon (categorie)+>
    <!ATTLIST rayon
        nom (homme|femme|enfant) #REQUIRED>

    <!ELEMENT categorie (type)+>
    <!ATTLIST categorie
        nom CDATA #REQUIRED>

    <!ELEMENT type (article)+>
    <!ATTLIST type
        nom CDATA #REQUIRED>

    <!ELEMENT article (nom,marque,prix,promotion?,couleurs,image,avis)>
    <!ATTLIST article
        id ID #REQUIRED
        quantite CDATA #REQUIRED>

    <!ELEMENT nom (#PCDATA)>
    <!ATTLIST nom
        quantite CDATA #IMPLIED>

    <!ELEMENT marque (#PCDATA)>
    <!ATTLIST marque
        quantite CDATA #IMPLIED>

    <!ELEMENT prix (#PCDATA)>
    <!ATTLIST prix>

    <!ELEMENT promotion (#PCDATA)>
    <!ATTLIST promotion>

    <!ELEMENT couleurs (couleur)+>
    <!ATTLIST couleurs>

    <!ELEMENT couleur (#PCDATA)>
    <!ATTLIST couleur
        nomCSS CDATA #REQUIRED>

    <!ELEMENT image EMPTY>
    <!ATTLIST image
        src CDATA #REQUIRED>

    <!ELEMENT avis (commentaire)*>
    <!ATTLIST avis>

    <!ELEMENT commentaire (#PCDATA)>
    <!ATTLIST commentaire
        id ID #REQUIRED>

=== S41d/xmlproject/Projet.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE boutique SYSTEM 'Projet.dtd'>

<boutique>
  <rayon nom="homme">
    <categorie nom="v√™tements">
      <type nom="polaire">
        <article id="a_1564" quantite="20">
          <nom>Veste Polaire Chaude De Randonn√©e - SH100 U-WARM - HOMME</nom>
          <marque>QUECHUA</marque>
          <prix>35</prix>
          <couleurs>
            <couleur nomCSS="black">noir</couleur>
            <couleur nomCSS="blue">bleu</couleur>
            <couleur nomCSS="gray">gris</couleur>
            <couleur nomCSS="darkblue">blue-fonc√©</couleur>
          </couleurs>
          <image src="./images/a_1564_noir.webp"/>
          <avis>
            <commentaire id="c_1">produit de bonne qualit√©</commentaire>
          </avis>
        </article>
        <article id="a_1254" quantite="100">
          <nom>Polaire de randonn√©e - MH100 - Homme</nom>
          <marque>QUECHUA</marque>
          <prix>9</prix>
          <couleurs>
            <couleur nomCSS="black">noir</couleur>
            <couleur nomCSS="gray">gris</couleur>
          </couleurs>
          <image src="./images/a_1254_noir.webp"/>
          <avis>
            <commentaire id="c_178">produit de bonne qualit√©</commentaire>
          </avis>
        </article>
      </type>
      <type nom="surv√™tements">
        <article id="a_4564" quantite="200">
          <nom>Pantalon jogging Fitness Bas resserr√©</nom>
          <marque>NYAMBA</marque>
          <prix>10</prix>
          <couleurs>
            <couleur nomCSS="black">noir</couleur>
            <couleur nomCSS="gray">gris</couleur>
          </couleurs>
          <image src="./images/a_4564_noir.webp"/>
          <avis>
            <commentaire id="c_12">jolie produit</commentaire>
          </avis>
        </article>
        <article id="a_8565" quantite="120">
          <nom>PANTALON DE SURV√äTEMENT PUMA FITNESS</nom>
          <marque>PUMA</marque>
          <prix>40</prix>
          <promotion>25</promotion>
          <couleurs>
            <couleur nomCSS="black">noir</couleur>
          </couleurs>
          <image src="./images/a_8565_noir.webp"/>
          <avis>
            <commentaire id="c_123">Tres confortable</commentaire>
          </avis>
        </article>
      </type>
      <type nom="pantalons">
        <article id="a_4668" quantite="752">
          <nom>Pantalon cargo de trek voyage - TRAVEL 100 Homme</nom>
          <marque>FORCLAZ</marque>
          <prix>30</prix>
          <couleurs>
            <couleur nomCSS="gray">gris</couleur>
            <couleur nomCSS="brown">marron</couleur>
          </couleurs>
          <image src="./images/a_4668_gris.webp"/>
          <avis>
            <commentaire id="c_1234">Concernant Pantalon cargo de trek voyage - TRAVEL 100 gris Homme</commentaire>
          </avis>
        </article>
        <article id="a_7589" quantite="500">
          <nom>PANTALON CHAUD D√âPERLANT DE RANDONN√âE NEIGE - SH500 X-WARM - STRETCH HOMME</nom>
          <marque>QUECHUA</marque>
          <prix>50</prix>
          <couleurs>
            <couleur nomCSS="black">noir</couleur>
            <couleur nomCSS="gray">gris</couleur>
          </couleurs>
          <image src="./images/a_7589_noir.webp"/>
          <avis>
            <commentaire id="c_1235">Mon fils le met pour le sport au coll√®ge. Il est tr√®s content, car souple, s'adapte
              aux mouvements. Il tient chaud et surtout, il est facile d'entretien.
            </commentaire>
          </avis>
        </article>
      </type>
      <type nom="sous-v√™tements thermiques">
        <article id="a_7895" quantite="45">
          <nom>Sous-v√™tement de ski homme haut 100 Noir</nom>
          <marque>WEDZE</marque>
          <prix>6</prix>
          <couleurs>
            <couleur nomCSS="black">noir</couleur>
          </couleurs>
          <image src="./images/a_7895_noir.webp"/>
          <avis>
            <commentaire id="c_1236">produit correspondant √† mon attente</commentaire>
            <commentaire id="c_1237">Tient bien le chaud !</commentaire>
          </avis>
        </article>
        <article id="a_5785" quantite="20">
          <nom>Sous-v√™tement de ski homme 500 haut noir</nom>
          <marque>WEDZE</marque>
          <prix>13</prix>
          <couleurs>
            <couleur nomCSS="black">noir</couleur>
          </couleurs>
          <image src="./images/a_5785_noir.webp"/>
          <avis>
            <commentaire id="c_1238">Top</commentaire>
            <commentaire id="c_1239">Je recommande vivement</commentaire>
            <commentaire id="c_1240">l√©ger mais tr√®s chaud , parfait pour skier ou marcher</commentaire>
          </avis>
        </article>
        <article id="a_9566" quantite="100">
          <nom>Sous-v√™tement de ski homme 500 bas noir</nom>
          <marque>WEDZE</marque>
          <prix>13</prix>
          <couleurs>
            <couleur nomCSS="black">noir</couleur>
          </couleurs>
          <image src="./images/a_9566_noir.webp"/>
          <avis>
            <commentaire id="c_1241">bon rapport qualit√© prix confortable et robuste, bien chaud j'en suis vraiment
              contente
            </commentaire>
            <commentaire id="c_1242">Satisfait</commentaire>
          </avis>
        </article>
      </type>
      <type nom="tee-shirts">
        <article id="a_7894" quantite="45">
          <nom>T-shirt fitness Sportee manches courtes slim coton col rond homme</nom>
          <marque>NYAMBA</marque>
          <prix>3</prix>
          <couleurs>
            <couleur nomCSS="black">noir</couleur>
            <couleur nomCSS="gray">gris</couleur>
            <couleur nomCSS="darkblue">bleu-noir</couleur>
          </couleurs>
          <image src="./images/a_7894_noir.webp"/>
          <avis>
            <commentaire id="c_1250">Pas tr√®s long</commentaire>
            <commentaire id="c_1251">N‚Äôest pas tr√®s long, mais fait le job</commentaire>
          </avis>
        </article>
      </type>
    </categorie>
    <categorie nom="chaussant">
      <type nom="apr√®s-ski">
        <article id="a_4566" quantite="70">
          <nom>Chaussures chaudes et imperm√©ables de randonn√©e - SH100 X-WARM</nom>
          <marque>QUECHUA</marque>
          <prix>50</prix>
          <couleurs>
            <couleur nomCSS="green">vert</couleur>
            <couleur nomCSS="beige">beige</couleur>
            <couleur nomCSS="gray">gris</couleur>
            <couleur nomCSS="blue">bleu</couleur>
          </couleurs>
          <image src="./images/a_4566_vert.webp"/>
          <avis>
            <commentaire id="c_1254">Rapport qualit√© prix excellent</commentaire>
            <commentaire id="c_1255">Test√© sur 20 km √† -2¬∞. M√™me pas froidüëãüëã</commentaire>
          </avis>
        </article>
        <article id="a_5578" quantite="50">
          <nom>Bottes CHAUDE Solden</nom>
          <marque>MEINDL</marque>
          <prix>120</prix>
          <couleurs>
            <couleur nomCSS="brown">marron</couleur>
          </couleurs>
          <image src="./images/a_5578_marron.webp"/>
          <avis>
            <commentaire id="c_1256">deux fois utilis√©es deux fois elles ont pris l eau</commentaire>
            <commentaire id="c_1257">Je les ai depuis quelques mois et pas top,m√™me en mettant des chaussettes
              thermique.j'ai les pieds tjrs geler....
            </commentaire>
            <commentaire id="c_1258">excellentes pompes</commentaire>
          </avis>
        </article>
      </type>
      <type nom="baskets">
        <article id="a_454" quantite="55">
          <nom>Chaussures marche sportive homme Adidas vs pace</nom>
          <marque>ADIDAS</marque>
          <prix>60</prix>
          <couleurs>
            <couleur nomCSS="gray">gris</couleur>
          </couleurs>
          <image src="./images/a_454_gris.webp"/>
          <avis>

          </avis>
        </article>
        <article id="a_456" quantite="10">
          <nom>CHAUSSURE DE RUNNING HOMME RUN ACTIVE GRIP NOIR GRIS</nom>
          <marque>KALENJI</marque>
          <prix>35</prix>
          <couleurs>
            <couleur nomCSS="black">noir</couleur>
            <couleur nomCSS="white">blanc</couleur>
            <couleur nomCSS="cyan">bleu-turquoise</couleur>
            <couleur nomCSS="green">vert</couleur>
          </couleurs>
          <image src="./images/a_456_blanc.webp"/>
          <avis>
            <commentaire id="c_1252">Tr√®s bien pour le prix</commentaire>
            <commentaire id="c_1253">Bien</commentaire>
          </avis>
        </article>
        <article id="a_4546" quantite="20">
          <nom>Chaussures marche active homme HW 100</nom>
          <marque>NEWFEEL</marque>
          <prix>20</prix>
          <couleurs>
            <couleur nomCSS="black">noir</couleur>
          </couleurs>
          <image src="./images/a_4546_noir.webp"/>
          <avis>
            <commentaire id="c_1280">Pas cher et l√©g√®re voir si elle tient dans le temps</commentaire>
            <commentaire id="c_1259">Bien</commentaire>
          </avis>
        </article>
      </type>
      <type nom="sandales">
        <article id="a_4555" quantite="40">
          <nom>Sandales de randonn√©e - NH120 - Homme</nom>
          <marque>QUECHUA</marque>
          <prix>30</prix>
          <promotion>25</promotion>
          <couleurs>
            <couleur nomCSS="brown">marron</couleur>
          </couleurs>
          <image src="./images/a_4555_marron.webp"/>
          <avis>

          </avis>
        </article>
        <article id="a_7859" quantite="40">
          <nom>Sandales de randonn√©e - NH100 - Homme</nom>
          <marque>QUECHUA</marque>
